<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="797" started-at="2019-04-01T04:36:36Z" finished-at="2019-04-01T04:36:37Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="797" started-at="2019-04-01T04:36:36Z" finished-at="2019-04-01T04:36:37Z">
      <class name="framework_testng.DP.DataProvider_With_Excel_Intergration">
        <test-method status="PASS" signature="setUpBeforeClass()[pri:0, instance:framework_testng.DP.DataProvider_With_Excel_Intergration@523884b2]" name="setUpBeforeClass" is-config="true" duration-ms="764" started-at="2019-04-01T04:36:36Z" finished-at="2019-04-01T04:36:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method status="PASS" signature="tearDownAfterClass()[pri:0, instance:framework_testng.DP.DataProvider_With_Excel_Intergration@523884b2]" name="tearDownAfterClass" is-config="true" duration-ms="17" started-at="2019-04-01T04:36:37Z" finished-at="2019-04-01T04:36:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownAfterClass -->
        <test-method status="SKIP" signature="Test_Data(java.lang.String, java.lang.String)[pri:0, instance:framework_testng.DP.DataProvider_With_Excel_Intergration@523884b2]" name="Test_Data" duration-ms="0" started-at="2019-04-01T04:36:37Z" data-provider="userdata" finished-at="2019-04-01T04:36:37Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 1
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)
at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:924)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
at framework_testng.DP.DataProvider_With_Excel_Intergration.userdata(DataProvider_With_Excel_Intergration.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_Data -->
      </class> <!-- framework_testng.DP.DataProvider_With_Excel_Intergration -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
